-- Seed data for local/dev Supabase databases.
-- Run after schema.sql. Safe to re-run: upserts on primary key.

insert into recipes (id, name, cook_time_min, servings, tags, ingredients, prep_steps, instructions) values
  ('dal-tadka', 'Dal Tadka', 25, 4, array['dal', 'vegetarian', 'weeknight'], '[{"name":"Toor dal","qty":"1 cup"},{"name":"Turmeric","qty":"1/2 tsp"},{"name":"Salt","qty":"to taste"},{"name":"Onion","qty":"1, chopped"},{"name":"Tomato","qty":"1, chopped"},{"name":"Ginger-garlic paste","qty":"1 tbsp"},{"name":"Cumin seeds","qty":"1 tsp"},{"name":"Ghee","qty":"2 tbsp"},{"name":"Dried red chilies","qty":"2"},{"name":"Garam masala","qty":"1/2 tsp"},{"name":"Cilantro","qty":"for garnish"}]'::jsonb, '[{"text":"Soak toor dal in water for 30 minutes (or overnight in the fridge)","nightBefore":true},{"text":"Chop onion and tomato, mince ginger-garlic ahead","nightBefore":false},{"text":"Measure turmeric and garam masala into a small bowl","nightBefore":false}]'::jsonb, 'Rinse the soaked dal and add it to the Instant Pot with 3 cups water, turmeric, and salt. Pressure cook on High for 8 minutes, then let it natural release for 10 minutes. Meanwhile heat ghee in a small pan, add cumin seeds and dried chilies, then onion, ginger-garlic, and tomato; cook until soft and fragrant. Stir the tempering into the dal, add garam masala, and finish with cilantro.'),
  ('chana-masala', 'Chana Masala', 45, 4, array['legumes', 'vegan', 'meal-prep'], '[{"name":"Dried chickpeas","qty":"1.5 cups, soaked"},{"name":"Onion","qty":"1 large, chopped"},{"name":"Tomato","qty":"2, pureed"},{"name":"Ginger-garlic paste","qty":"1 tbsp"},{"name":"Cumin seeds","qty":"1 tsp"},{"name":"Coriander powder","qty":"1 tbsp"},{"name":"Red chili powder","qty":"1 tsp"},{"name":"Turmeric","qty":"1/2 tsp"},{"name":"Chana masala spice mix","qty":"1.5 tbsp"},{"name":"Oil","qty":"2 tbsp"},{"name":"Salt","qty":"to taste"},{"name":"Cilantro","qty":"for garnish"},{"name":"Lemon","qty":"for garnish"}]'::jsonb, '[{"text":"Soak chickpeas in water overnight (8+ hours)","nightBefore":true},{"text":"Chop the onion and puree the tomatoes ahead","nightBefore":false},{"text":"Portion the spice mix into a small bowl","nightBefore":false}]'::jsonb, 'Set to Sauté, heat oil, and cook cumin seeds, onion, and ginger-garlic until golden. Add tomato puree and spices, cooking 3-4 minutes. Add drained chickpeas and 2 cups water. Pressure cook on High for 20 minutes, natural release 15 minutes. Mash a few chickpeas to thicken the sauce, then finish with cilantro and a squeeze of lemon.'),
  ('jeera-rice', 'Jeera Rice', 20, 4, array['rice', 'side', 'quick'], '[{"name":"Basmati rice","qty":"1.5 cups"},{"name":"Cumin seeds","qty":"1.5 tsp"},{"name":"Ghee","qty":"2 tbsp"},{"name":"Whole spices (bay leaf, cloves, cardamom)","qty":"1 set"},{"name":"Salt","qty":"to taste"}]'::jsonb, '[{"text":"Rinse and soak basmati rice for 20 minutes, then drain","nightBefore":false}]'::jsonb, 'Set to Sauté, melt ghee, and toast cumin seeds with the whole spices until fragrant. Add the drained rice and stir for a minute to coat. Add 2 cups water and salt. Pressure cook on High for 4 minutes, natural release 8 minutes, then fluff with a fork.'),
  ('rajma', 'Rajma (Kidney Bean Curry)', 50, 4, array['legumes', 'vegan', 'freezer-friendly'], '[{"name":"Dried kidney beans","qty":"1.5 cups, soaked"},{"name":"Onion","qty":"1, chopped"},{"name":"Tomato","qty":"2, pureed"},{"name":"Ginger-garlic paste","qty":"1 tbsp"},{"name":"Cumin seeds","qty":"1 tsp"},{"name":"Coriander powder","qty":"1 tbsp"},{"name":"Red chili powder","qty":"1 tsp"},{"name":"Garam masala","qty":"1 tsp"},{"name":"Oil","qty":"2 tbsp"},{"name":"Salt","qty":"to taste"},{"name":"Cilantro","qty":"for garnish"}]'::jsonb, '[{"text":"Soak rajma in water overnight (8+ hours)","nightBefore":true},{"text":"Chop the onion and puree the tomatoes ahead","nightBefore":false},{"text":"Mince ginger and garlic ahead","nightBefore":false}]'::jsonb, 'Sauté cumin seeds, onion, and ginger-garlic until golden. Add tomato puree and spices, cooking until the oil separates. Add drained rajma and 2.5 cups water. Pressure cook on High for 25 minutes, natural release 15 minutes. Mash slightly to thicken, then finish with garam masala and cilantro.')
on conflict (id) do update set
  name = excluded.name, cook_time_min = excluded.cook_time_min, servings = excluded.servings,
  tags = excluded.tags, ingredients = excluded.ingredients, prep_steps = excluded.prep_steps,
  instructions = excluded.instructions;

-- `days` holds an array of assignments per day (usually 0 or 1, but a day can
-- have several meals across lunch/dinner) — see lib/types.ts's Days/
-- Assignment types.
insert into mealplans (week_id, days) values
  ('2026-09-07', '{"Mon":[{"id":"a-seed0001","recipeId":"dal-tadka","mealSlot":"dinner","prepDone":[false,false,false]}],"Tue":[],"Wed":[{"id":"a-seed0002","recipeId":"chana-masala","mealSlot":"dinner","prepDone":[false,false,false]}],"Thu":[],"Fri":[{"id":"a-seed0003","recipeId":"rajma","mealSlot":"dinner","prepDone":[false,false,false]}],"Sat":[{"id":"a-seed0004","recipeId":"jeera-rice","mealSlot":"lunch","prepDone":[false]}],"Sun":[]}'::jsonb)
on conflict (week_id) do update set days = excluded.days;
